import { createClient } from "@supabase/supabase-js";
import { generateText, gateway, Output } from "ai";
import { NextResponse } from "next/server";
import { z } from "zod";

export const runtime = "nodejs";
const reviewSchema=z.object({summary:z.string(),recommendations:z.array(z.object({section:z.string(),finding:z.string(),proposedChange:z.string(),evidence:z.string(),priority:z.enum(["alta","media","baja"])})).min(3).max(10)});
export async function GET(request:Request){
 if(!process.env.CRON_SECRET||request.headers.get("authorization")!==`Bearer ${process.env.CRON_SECRET}`)return NextResponse.json({error:"No autorizado."},{status:401});
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return NextResponse.json({error:"Supabase no configurado."},{status:503});const admin=createClient(url,key,{auth:{autoRefreshToken:false,persistSession:false}});const today=new Date();const period=`${today.getUTCFullYear()}-${String(today.getUTCMonth()+1).padStart(2,"0")}-01`;
 const existing=await admin.from("academy_review_runs").select("id").eq("review_period",period).maybeSingle();if(existing.data)return NextResponse.json({ok:true,skipped:"already-reviewed"});
 const since=new Date(Date.now()-62*86_400_000).toISOString();const [{data:speeches},{data:sales},{data:tasks},{data:communications}]=await Promise.all([admin.from("opportunity_speech_usage").select("stage,channel,outcome,speech_id,used_at").gte("used_at",since),admin.from("sales_reports").select("seller_id,closed_at,initial_fee,final_fee,commission_amount").gte("closed_at",since),admin.from("tasks").select("status,priority,outcome,created_at").gte("created_at",since),admin.from("communications").select("channel,status,template_key,created_at").gte("created_at",since)]);const evidence={periodStart:since,speeches:speeches??[],sales:sales??[],tasks:tasks??[],communications:communications??[]};
 try{const {output}=await generateText({model:gateway("openai/gpt-5-mini"),output:Output.object({schema:reviewSchema}),instructions:"Actúa como responsable de enablement de ventas B2B éticas para INDEX CONDO. Analiza únicamente métricas agregadas del CRM. Propón mejoras prácticas para academia, speeches y proceso. No inventes casos de éxito ni recomiendes manipulación. Toda propuesta será un borrador sujeto a aprobación humana.",prompt:JSON.stringify(evidence)});const inserted=await admin.from("academy_review_runs").insert({review_period:period,status:"borrador",source_summary:{summary:output.summary,counts:{speeches:speeches?.length??0,sales:sales?.length??0,tasks:tasks?.length??0,communications:communications?.length??0}},recommendations:output.recommendations}).select("id").single();if(inserted.error)throw inserted.error;return NextResponse.json({ok:true,id:inserted.data.id,recommendations:output.recommendations.length})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"No fue posible generar la revisión."},{status:500})}
}
