"use client";
import Link from "next/link";
import { Building2, Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useCrm } from "@/components/crm-provider";
import { Modal, PageHeader, StagePill } from "@/components/ui";
import { accountTypeLabels, formatCurrency } from "@/lib/constants";
import { calculateOpportunityScore } from "@/lib/opportunity-score";
import { accountSchema } from "@/lib/validation";
import type { AccountType } from "@/types/domain";

export default function ProspectosPage() {
  const { accounts, opportunities, stakeholders, proposals, tasks, addProspect, currentUser } = useCrm(); const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const [type,setType]=useState("todos"); const [errors,setErrors]=useState<Record<string,string>>({});
  useEffect(()=>{if(new URLSearchParams(window.location.search).get("nuevo")) setOpen(true)},[]);
  const rows=useMemo(()=>accounts.filter((account)=>account.name.toLowerCase().includes(query.toLowerCase())&&(type==="todos"||account.accountType===type)),[accounts,query,type]);
  function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const values=Object.fromEntries(form);const parsed=accountSchema.safeParse(values);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map((i)=>[String(i.path[0]),i.message])));return}const now=Date.now().toString();const accountId=`a${now}`;const opportunityId=`o${now}`;addProspect({account:{id:accountId,name:parsed.data.name,accountType:parsed.data.accountType as AccountType,address:String(values.address||""),sector:parsed.data.sector,city:"Santo Domingo",units:parsed.data.units,towers:Number(values.towers||1),profile:String(values.profile||"familiar"),ownerId:currentUser.id,source:String(values.source||"Directo"),createdAt:new Date().toISOString()},stakeholder:{id:`s${now}`,accountId,fullName:parsed.data.stakeholderName,role:"presidente",phone:String(values.phone||""),email:parsed.data.stakeholderEmail,influence:5,position:"unknown",isDecisionMaker:true},opportunity:{id:opportunityId,accountId,stage:"prospecto_identificado",primaryProblem:parsed.data.primaryProblem,impact:"Pendiente de diagnóstico",proposedSolution:"Pendiente de diagnóstico",monthlyFee:0,probability:15,nextAction:parsed.data.nextAction,nextActionAt:new Date(parsed.data.nextActionAt).toISOString(),ownerId:currentUser.id,updatedAt:new Date().toISOString()}});setOpen(false);setErrors({});}
  return <><PageHeader eyebrow="Cuentas B2B" title="Prospectos y cuentas" description="Condominios, torres, residenciales y proyectos con todos sus decisores y oportunidades."><button className="button button-primary" onClick={()=>setOpen(true)}><Plus size={18}/> Registrar prospecto</button></PageHeader><div className="toolbar"><label className="search"><Search size={18}/><input placeholder="Buscar por nombre del condominio…" value={query} onChange={(e)=>setQuery(e.target.value)}/></label><select className="filter-select" value={type} onChange={(e)=>setType(e.target.value)}><option value="todos">Todos los segmentos</option>{Object.entries(accountTypeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div><div className="card table-wrap"><table className="table"><thead><tr><th>Cliente potencial</th><th>Segmento</th><th>Unidades</th><th>Necesidad principal</th><th>Etapa</th><th>Probabilidad</th><th>Valor mensual</th></tr></thead><tbody>{rows.map((account)=>{const opportunity=opportunities.find((o)=>o.accountId===account.id);const score=opportunity?calculateOpportunityScore(opportunity,stakeholders,proposals,tasks).score:0;return <tr key={account.id}><td><Link className="account-name" href={`/prospectos/${account.id}`}><span className="account-icon"><Building2 size={18}/></span><span><strong>{account.name}</strong><small>{account.sector} · {account.source}</small></span></Link></td><td>{accountTypeLabels[account.accountType]}</td><td>{account.units}</td><td>{opportunity?.primaryProblem}</td><td>{opportunity&&<StagePill stage={opportunity.stage}/>}</td><td><b>{score}%</b><div className="progress"><span style={{width:`${score}%`}}/></div></td><td className="amount">{formatCurrency(opportunity?.monthlyFee??0)}</td></tr>})}</tbody></table></div>
    {open&&<Modal title="Registrar prospecto B2B" description="Crea la cuenta, el decisor inicial y la primera próxima acción." onClose={()=>setOpen(false)} wide><form onSubmit={submit}><div className="form-grid"><Field name="name" label="Nombre del condominio o proyecto" error={errors.name}/><label className="field"><span>Tipo de cuenta</span><select name="accountType" defaultValue="condominio_existente">{Object.entries(accountTypeLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><Field name="sector" label="Sector" error={errors.sector}/><Field name="address" label="Dirección"/><Field name="units" type="number" label="Cantidad de unidades" error={errors.units}/><Field name="towers" type="number" label="Cantidad de torres" defaultValue="1"/><label className="field"><span>Perfil</span><select name="profile"><option value="familiar">Familiar</option><option value="premium">Premium</option><option value="corporativo">Corporativo</option></select></label><Field name="source" label="Fuente del prospecto" defaultValue="Referido"/><Field name="stakeholderName" label="Contacto / decisor principal" error={errors.stakeholderName}/><Field name="stakeholderEmail" type="email" label="Correo del contacto" error={errors.stakeholderEmail}/><Field name="phone" label="Teléfono / WhatsApp"/><label className="field field-wide"><span>Necesidad principal</span><textarea name="primaryProblem" placeholder="¿Qué problema desea resolver el condominio?"/>{errors.primaryProblem&&<small className="field-error">{errors.primaryProblem}</small>}</label><Field name="nextAction" label="Próxima acción obligatoria" error={errors.nextAction}/><Field name="nextActionAt" type="datetime-local" label="Fecha y hora" error={errors.nextActionAt}/></div><div className="form-actions"><button type="button" className="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="button button-primary">Crear prospecto</button></div></form></Modal>}
  </>;
}

function Field({name,label,type="text",error,defaultValue}:{name:string;label:string;type?:string;error?:string;defaultValue?:string}){return <label className="field"><span>{label}</span><input name={name} type={type} defaultValue={defaultValue}/>{error&&<small className="field-error">{error}</small>}</label>}
