"use client";
import { Shield, UserPlus } from "lucide-react";
import { useState } from "react";
import { useCrm } from "@/components/crm-provider";
import { Modal, PageHeader } from "@/components/ui";
import { roleLabels } from "@/lib/constants";
import { canManageUsers } from "@/lib/permissions";
import type { UserRole } from "@/types/domain";

export default function UsuariosPage(){const {users,currentUser,toggleUser,addUser}=useCrm();const [open,setOpen]=useState(false);const canManage=canManageUsers(currentUser);function invite(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);addUser({id:`u${Date.now()}`,fullName:String(form.get("fullName")),email:String(form.get("email")),role:String(form.get("role")) as UserRole,active:true});setOpen(false)}return <><PageHeader eyebrow="Seguridad y acceso" title="Usuarios, roles y permisos" description="El superadministrador controla el acceso; cada ejecutivo ve únicamente la cartera asignada."><button className="button button-primary" disabled={!canManage} onClick={()=>setOpen(true)}><UserPlus size={18}/> Invitar usuario</button></PageHeader><div className="card table-wrap"><table className="table"><thead><tr><th>Usuario</th><th>Rol</th><th>Estado</th><th>Alcance</th><th>Acción</th></tr></thead><tbody>{users.map((user)=><tr key={user.id}><td><div className="role-card"><span className="avatar">{user.fullName.split(" ").map((n)=>n[0]).slice(0,2).join("")}</span><span><strong>{user.fullName}</strong><small>{user.email}</small></span></div></td><td><Shield size={14} color="#145da0"/> {roleLabels[user.role]}</td><td><span className={`status-pill ${user.active?"status-active":"status-inactive"}`}>{user.active?"Activo":"Desactivado"}</span></td><td>{user.role==="ejecutivo"?"Prospectos asignados":user.role==="consulta"?"Solo lectura":"Todo el CRM"}</td><td><button className={`button compact ${user.active?"button-danger":""}`} disabled={!canManage||user.id===currentUser.id} onClick={()=>toggleUser(user.id)}>{user.active?"Desactivar":"Activar"}</button></td></tr>)}</tbody></table></div>{!canManage&&<p style={{color:"#667085",fontSize:12}}>Estás viendo esta pantalla en modo consulta. Solo el superadministrador puede cambiar accesos.</p>}{open&&<Modal title="Invitar usuario" description="Define su rol y acceso inicial al CRM." onClose={()=>setOpen(false)}><form onSubmit={invite}><div className="form-grid"><label className="field field-wide"><span>Nombre completo</span><input name="fullName" required/></label><label className="field field-wide"><span>Correo corporativo</span><input name="email" type="email" required/></label><label className="field field-wide"><span>Rol</span><select name="role" defaultValue="ejecutivo">{Object.entries(roleLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><div className="form-actions"><button type="button" className="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="button button-primary">Crear usuario</button></div></form></Modal>}</>}
