"use client";
import { BadgeCheck, Banknote, CircleDollarSign, ReceiptText } from "lucide-react";
import { useMemo } from "react";
import { PageHeader } from "@/components/ui";
import { useCrm } from "@/components/crm-provider";
import { formatCurrency } from "@/lib/constants";

const statusLabels = { proyectada:"Proyectada", ganada:"Ganada", pagadera:"Pagadera", pagada:"Pagada", revertida:"Revertida" };
export default function VentasPage(){const {salesReports,accounts,users,currentUser,confirmFirstPayment,markCommissionPaid}=useCrm();const manager=["superadmin","gerencia_comercial","administracion"].includes(currentUser.role);const reports=useMemo(()=>manager?salesReports:salesReports.filter((item)=>item.sellerId===currentUser.id),[manager,salesReports,currentUser.id]);const monthly=reports.reduce((sum,item)=>sum+item.finalFee,0);const commissions=reports.filter((item)=>item.commissionStatus==="pagadera").reduce((sum,item)=>sum+item.commissionAmount,0);return <><PageHeader eyebrow="Cierres auditables" title="Ventas y comisiones" description="Reporte comercial de cada cierre. La comisión corresponde al 50% del primer honorario mensual efectivamente cobrado."/><div className="grid kpi-grid"><Kpi icon={<ReceiptText/>} label="Ventas cerradas" value={String(reports.length)}/><Kpi icon={<Banknote/>} label="Ingreso mensual cerrado" value={formatCurrency(monthly)}/><Kpi icon={<CircleDollarSign/>} label="Valor anual" value={formatCurrency(monthly*12)}/><Kpi icon={<BadgeCheck/>} label="Comisiones pagaderas" value={formatCurrency(commissions)}/></div><div className="card table-wrap"><table className="table sales-table"><thead><tr><th>Cliente / contrato</th><th>Vendedor</th><th>Cierre</th><th>Inicial</th><th>Final</th><th>Variación</th><th>Comisión 50%</th><th>Estado</th>{manager&&<th>Control</th>}</tr></thead><tbody>{reports.map((report)=>{const account=accounts.find((item)=>item.id===report.accountId);const seller=users.find((item)=>item.id===report.sellerId);const variation=report.initialFee?((report.finalFee-report.initialFee)/report.initialFee)*100:0;return <tr key={report.id}><td><strong>{account?.name??"Cuenta"}</strong><small>{report.contractReference}</small></td><td><strong>{seller?.fullName??"Vendedor"}</strong></td><td>{new Date(report.closedAt).toLocaleDateString("es-DO")}</td><td className="amount">{formatCurrency(report.initialFee)}</td><td className="amount">{formatCurrency(report.finalFee)}</td><td className={variation<0?"negative":"positive"}>{variation.toFixed(1)}%</td><td className="amount">{formatCurrency(report.commissionAmount)}</td><td><span className={`status-pill commission-${report.commissionStatus}`}>{statusLabels[report.commissionStatus]}</span></td>{manager&&<td>{report.commissionStatus==="ganada"&&<button className="button compact" onClick={()=>confirmFirstPayment(report.id)}>Confirmar cobro</button>}{report.commissionStatus==="pagadera"&&<button className="button button-primary compact" onClick={()=>markCommissionPaid(report.id)}>Marcar pagada</button>}{report.commissionStatus==="pagada"&&<small>{report.commissionPaidAt&&new Date(report.commissionPaidAt).toLocaleDateString("es-DO")}</small>}</td>}</tr>})}</tbody></table>{reports.length===0&&<div className="empty-state"><b>Aún no hay ventas cerradas</b><p>El primer reporte aparecerá al completar un cierre desde el expediente del prospecto.</p></div>}</div></>}
function Kpi({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article className="card kpi-card"><div className="kpi-top"><span className="kpi-label">{label}</span><span className="kpi-icon">{icon}</span></div><div className="kpi-value">{value}</div><div className="kpi-foot">Registro comercial verificable</div></article>}
