"use client";
import { CheckCircle2, Clock3, Mail, MessageCircle, Plus, Search, Send, ShieldCheck, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Modal, PageHeader } from "@/components/ui";
import { useCrm } from "@/components/crm-provider";
import { communicationTemplates, renderCommunicationTemplate } from "@/lib/communication-templates";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";
import { mapCommunication } from "@/lib/supabase/mappers";
import type { Communication } from "@/types/domain";
const statusLabels:Record<string,string>={draft:"Borrador",queued:"En cola",sent:"Enviado",delivered:"Entregado",opened:"Abierto",delayed:"Demorado",bounced:"Rebotado",failed:"Fallido",complained:"Reportado",received:"Recibido"};

export default function CommunicationsPage(){
  const {accounts,opportunities,stakeholders}=useCrm();const [tab,setTab]=useState<"email"|"whatsapp">("email");const [open,setOpen]=useState(false);const [messages,setMessages]=useState<Communication[]>([]);const [loading,setLoading]=useState(isSupabaseConfigured);const [error,setError]=useState("");const [query,setQuery]=useState("");const [selectedOpportunity,setSelectedOpportunity]=useState("");const [selectedStakeholder,setSelectedStakeholder]=useState("");const [template,setTemplate]=useState("seguimiento");const [subject,setSubject]=useState("");const [body,setBody]=useState("");const [sending,setSending]=useState(false);
  const load=useCallback(async()=>{const supabase=createClient();if(!supabase){setLoading(false);return}const {data,error}=await supabase.from("communications").select("*").order("created_at",{ascending:false});if(error)setError(error.message);else setMessages((data??[]).map((row)=>mapCommunication(row)));setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const activeOpportunity=opportunities.find((item)=>item.id===selectedOpportunity);const account=accounts.find((item)=>item.id===activeOpportunity?.accountId);const contacts=stakeholders.filter((item)=>item.accountId===account?.id&&Boolean(item.email));const filtered=useMemo(()=>messages.filter((item)=>`${item.subject} ${item.toAddress} ${item.bodyText}`.toLowerCase().includes(query.toLowerCase())),[messages,query]);
  function chooseOpportunity(value:string){setSelectedOpportunity(value);const opp=opportunities.find((item)=>item.id===value);const acct=accounts.find((item)=>item.id===opp?.accountId);const contact=stakeholders.find((item)=>item.accountId===acct?.id&&item.email);setSelectedStakeholder(contact?.id??"");const rendered=renderCommunicationTemplate(template,acct?.name??"el condominio",contact?.fullName??"cliente");setSubject(rendered.subject);setBody(rendered.body)}
  function chooseTemplate(value:string){setTemplate(value);const contact=stakeholders.find((item)=>item.id===selectedStakeholder);const rendered=renderCommunicationTemplate(value,account?.name??"el condominio",contact?.fullName??"cliente");setSubject(rendered.subject);setBody(rendered.body)}
  function openComposer(){const first=opportunities[0];setOpen(true);setError("");if(first)chooseOpportunity(first.id)}
  async function sendEmail(event:React.FormEvent){event.preventDefault();setSending(true);setError("");const response=await fetch("/api/communications/email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({opportunityId:selectedOpportunity,stakeholderId:selectedStakeholder,templateKey:template,subject,body})});const result=await response.json();if(!response.ok){setError(result.error??"No fue posible enviar el correo.");setSending(false);return}setMessages((items)=>[mapCommunication(result.communication),...items]);setSending(false);setOpen(false)}
  const sent=messages.filter((item)=>item.channel==="email").length;const delivered=messages.filter((item)=>["delivered","opened"].includes(item.status)).length;const attention=messages.filter((item)=>["failed","bounced","complained"].includes(item.status)).length;
  return <><PageHeader eyebrow="Expediente omnicanal" title="Comunicaciones con clientes" description="El correo conserva la conversación formal; WhatsApp complementa el seguimiento inmediato sin perder trazabilidad."><button className="button button-primary" onClick={openComposer}><Plus size={18}/> Redactar correo</button></PageHeader>{error&&!open&&<div className="sync-banner sync-error">{error}</div>}<div className="channel-tabs"><button className={tab==="email"?"active":""} onClick={()=>setTab("email")}><Mail size={17}/> Correo formal</button><button className={tab==="whatsapp"?"active":""} onClick={()=>setTab("whatsapp")}><MessageCircle size={17}/> WhatsApp</button></div>
    {tab==="email"?<><div className="grid communications-kpis"><Metric icon={<Send/>} label="Correos registrados" value={String(sent)}/><Metric icon={<CheckCircle2/>} label="Entregados / abiertos" value={String(delivered)}/><Metric icon={<XCircle/>} label="Requieren atención" value={String(attention)}/></div><div className="toolbar"><label className="search"><Search size={18}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por cliente, asunto o destinatario…"/></label></div><div className="card communication-list">{loading?<div className="empty-state"><b>Cargando comunicaciones…</b></div>:filtered.length===0?<div className="empty-state"><b>Aún no hay correos registrados</b><p>Redacta el primer mensaje formal desde este módulo.</p></div>:filtered.map((message)=>{const opportunity=opportunities.find((item)=>item.id===message.opportunityId);const acct=accounts.find((item)=>item.id===opportunity?.accountId);return <article className="communication-row" key={message.id}><span className="channel-icon"><Mail size={18}/></span><div><div className="communication-heading"><b>{message.subject}</b><span className={`status-pill message-${message.status}`}>{statusLabels[message.status]??message.status}</span></div><small>{acct?.name??"Cuenta"} · Para: {message.toAddress}</small><p>{message.bodyText.slice(0,180)}{message.bodyText.length>180?"…":""}</p><small><Clock3 size={11}/>{new Date(message.sentAt??message.createdAt).toLocaleString("es-DO")}{message.errorMessage&&` · ${message.errorMessage}`}</small></div></article>})}</div></>:<WhatsAppAssessment stakeholders={stakeholders}/>} 
    {open&&<Modal title="Redactar correo formal" description="El mensaje y su estado de entrega quedarán asociados al expediente comercial." onClose={()=>setOpen(false)} wide><form onSubmit={sendEmail}>{error&&<div className="sync-banner sync-error">{error}</div>}<div className="form-grid"><label className="field"><span>Oportunidad / cliente</span><select value={selectedOpportunity} onChange={(e)=>chooseOpportunity(e.target.value)} required>{opportunities.map((opp)=>{const acct=accounts.find((item)=>item.id===opp.accountId);return <option value={opp.id} key={opp.id}>{acct?.name}</option>})}</select></label><label className="field"><span>Destinatario</span><select value={selectedStakeholder} onChange={(e)=>setSelectedStakeholder(e.target.value)} required>{contacts.map((contact)=><option value={contact.id} key={contact.id}>{contact.fullName} · {contact.email}</option>)}</select></label><label className="field field-wide"><span>Plantilla</span><select value={template} onChange={(e)=>chooseTemplate(e.target.value)}>{communicationTemplates.map((item)=><option value={item.id} key={item.id}>{item.label}</option>)}</select></label><label className="field field-wide"><span>Asunto</span><input value={subject} onChange={(e)=>setSubject(e.target.value)} required/></label><label className="field field-wide"><span>Mensaje</span><textarea className="email-body" value={body} onChange={(e)=>setBody(e.target.value)} required/></label><div className="formal-note field-wide"><ShieldCheck size={16}/> Identidad INDEX CONDO · respuestas centralizadas en ventas@indexelemecsrl.com.</div></div><div className="form-actions"><button type="button" className="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="button button-primary" disabled={sending||!selectedStakeholder}>{sending?"Enviando…":<><Send size={16}/> Enviar y registrar</>}</button></div></form></Modal>}
  </>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <article className="card communication-metric"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>}
function WhatsAppAssessment({stakeholders}:{stakeholders:{phone:string}[]}){const withPhone=stakeholders.filter((item)=>item.phone).length;return <div className="whatsapp-grid"><section className="card whatsapp-recommendation"><div className="whatsapp-title"><MessageCircle size={28}/><div><span className="eyebrow">Evaluación recomendada</span><h2>WhatsApp como canal complementario</h2></div></div><p>Úsalo para confirmar reuniones, avisar que una propuesta fue enviada y responder consultas rápidas. El correo debe conservar propuestas, acuerdos, cambios de precio y aprobaciones.</p><div className="whatsapp-flow"><span>WhatsApp breve</span><b>→</b><span>Correo formal</span><b>→</b><span>Registro CRM</span></div><ul><li>{withPhone} contactos actuales tienen teléfono registrado.</li><li>Se requiere consentimiento para comunicaciones iniciadas por INDEX CONDO.</li><li>Fuera de la ventana de 24 horas se necesitan plantillas aprobadas.</li><li>Los mensajes entrantes y salientes deben llegar por webhook al expediente.</li></ul></section><section className="card provider-card"><h2>Ruta de implementación</h2><ol><li><b>Piloto:</b> Twilio Sandbox para validar textos, webhooks y experiencia.</li><li><b>Producción:</b> número corporativo, WhatsApp Business Account y plantillas.</li><li><b>CRM:</b> bandeja unificada, consentimiento, ventana activa y estados.</li></ol><div className="provider-decision"><CheckCircle2 size={18}/><span><b>Recomendación</b><small>Activarlo después de estabilizar el correo y aprobar 3 plantillas: seguimiento, reunión y propuesta enviada.</small></span></div></section></div>}
