"use client";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, Building2, CalendarPlus, FilePlus2, Lightbulb, Mail, Phone, RefreshCw, Users } from "lucide-react";
import { useParams } from "next/navigation";
import { useState } from "react";
import { useCrm } from "@/components/crm-provider";
import { Modal, StagePill } from "@/components/ui";
import { accountTypeLabels, formatCurrency, roleLabels } from "@/lib/constants";
import { recommendationForOpportunity, stagePlaybook } from "@/lib/sales-playbook";

export default function ProspectDetail(){
  const {id}=useParams<{id:string}>();
  const {accounts,opportunities,stakeholders,users,currentUser,proposals,salesReports,assignmentHistory,assignOpportunity,closeSale}=useCrm();
  const [assignOpen,setAssignOpen]=useState(false); const [closeOpen,setCloseOpen]=useState(false); const [notice,setNotice]=useState("");
  const account=accounts.find((a)=>a.id===id); const opportunity=opportunities.find((o)=>o.accountId===id)!;
  if(!account||!opportunity)return <div className="empty-state"><b>Prospecto no encontrado</b><p>El registro solicitado no existe o no está visible para este usuario.</p></div>;
  const contacts=stakeholders.filter((s)=>s.accountId===id); const owner=users.find((u)=>u.id===opportunity.ownerId); const playbook=stagePlaybook[opportunity.stage]; const recommendation=recommendationForOpportunity(opportunity); const report=salesReports.find((item)=>item.opportunityId===opportunity.id); const managers=["superadmin","gerencia_comercial"].includes(currentUser.role); const canClose=["superadmin","gerencia_comercial","ejecutivo"].includes(currentUser.role)&&!report&&opportunity.stage!=="perdida";
  const proposalHistory=proposals.filter((item)=>item.opportunityId===opportunity.id).sort((a,b)=>b.version-a.version); const defaultFee=proposalHistory[0]?.monthlyFee||opportunity.monthlyFee;
  function submitAssignment(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const seller=String(data.get("seller"));const reason=String(data.get("reason")).trim();if(!seller||reason.length<3){setNotice("Selecciona un vendedor e indica el motivo.");return}assignOpportunity(opportunity.id,seller,reason);setAssignOpen(false);setNotice("Responsable actualizado y cambio registrado.")}
  function submitClose(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const finalFee=Number(data.get("finalFee"));const contractReference=String(data.get("contractReference")).trim();if(finalFee<=0||contractReference.length<3){setNotice("Indica un monto válido y la referencia del contrato.");return}closeSale({opportunityId:opportunity.id,finalFee,contractReference,closedAt:String(data.get("closedAt")),firstPaymentReceived:data.get("firstPaymentReceived")==="on",notes:String(data.get("notes")||"")});setCloseOpen(false);setNotice("Venta cerrada. El reporte y la comisión fueron generados.")}
  return <><Link href="/prospectos" className="text-link back-link"><ArrowLeft size={14}/> Volver a prospectos</Link>{notice&&<div className="sync-banner">{notice}</div>}<section className="card detail-hero"><div className="detail-title"><span className="account-icon"><Building2 size={25}/></span><div><h1>{account.name}</h1><p>{accountTypeLabels[account.accountType]} · {account.sector}, {account.city}</p></div></div><div className="page-actions">{managers&&<button className="button" onClick={()=>setAssignOpen(true)}><RefreshCw size={17}/> Asignar vendedor</button>}<Link className="button" href="/tareas"><CalendarPlus size={17}/> Nueva tarea</Link><Link className="button" href={`/propuestas?nueva=${opportunity.id}`}><FilePlus2 size={17}/> Generar propuesta</Link>{canClose&&<button className="button button-primary" onClick={()=>setCloseOpen(true)}><BadgeCheck size={17}/> Cerrar venta</button>}</div></section>
    <div className="grid detail-grid"><div className="grid"><section className="card detail-section"><div className="split-heading"><h2>Oportunidad comercial</h2><StagePill stage={opportunity.stage}/></div><div className="facts"><div className="fact"><small>Honorarios estimados</small><b>{formatCurrency(opportunity.monthlyFee)}</b></div><div className="fact"><small>Probabilidad de cierre</small><b>{opportunity.probability}%</b></div><div className="fact"><small>Vendedor responsable</small><b>{owner?.fullName}</b></div><div className="fact"><small>Unidades / torres</small><b>{account.units} / {account.towers}</b></div></div><div className="problem-box"><small>PROBLEMA DETECTADO</small><p>{opportunity.primaryProblem}</p></div><div className="problem-box solution-box"><small>SOLUCIÓN RECOMENDADA</small><p>{opportunity.proposedSolution}</p></div></section>
      <section className="card coach-card"><div className="coach-title"><Lightbulb size={21}/><div><small>COACH COMERCIAL · {playbook.techniqueId.replaceAll("-"," ")}</small><h2>{playbook.objective}</h2></div></div><p className="coach-recommendation">{recommendation}</p><div className="coach-columns"><div><b>Acciones recomendadas</b><ol>{playbook.actions.map((action)=><li key={action}>{action}</li>)}</ol></div><div><b>Criterio para avanzar</b><p>{playbook.exitCriteria.join(" · ")}</p><Link className="text-link" href={`/academia#${playbook.techniqueId}`}>Estudiar técnica relacionada →</Link></div></div></section>
      <section className="card detail-section"><h2>Próxima acción obligatoria</h2><div className="next-item no-border"><div className="date-box"><b>{new Date(opportunity.nextActionAt).getDate()}</b><small>{new Date(opportunity.nextActionAt).toLocaleDateString("es-DO",{month:"short"})}</small></div><div><strong>{opportunity.nextAction}</strong><p>{new Date(opportunity.nextActionAt).toLocaleString("es-DO",{dateStyle:"medium",timeStyle:"short"})}</p></div></div></section>
      {report&&<section className="card sale-summary"><BadgeCheck size={26}/><div><small>VENTA CERRADA · {report.contractReference}</small><h2>{formatCurrency(report.finalFee)} mensuales</h2><p>Vendedor: {users.find((item)=>item.id===report.sellerId)?.fullName} · Comisión: {formatCurrency(report.commissionAmount)} ({report.commissionStatus})</p></div><Link className="button" href="/ventas">Ver reporte</Link></section>}</div>
      <aside className="grid"><section className="card detail-section"><div className="split-heading"><h2>Stakeholders y decisores</h2><Users size={18} color="#f47721"/></div>{contacts.map((contact)=><div className="stakeholder" key={contact.id}><span className="avatar">{contact.fullName.split(" ").map((n)=>n[0]).slice(0,2).join("")}</span><div className="stakeholder-info"><b>{contact.fullName}</b><small>{contact.role.replaceAll("_"," ")} {contact.isDecisionMaker&&"· Decisor"}</small><small><Phone size={10}/> {contact.phone} · <Mail size={10}/> {contact.email}</small></div><div className="influence" title={`Influencia ${contact.influence}/5`}>{[1,2,3,4,5].map((n)=><i className={n<=contact.influence?"on":""} key={n}/>)}</div></div>)}</section><section className="card detail-section"><h2>Datos de la cuenta</h2><div className="facts"><div className="fact"><small>Dirección</small><b>{account.address}</b></div><div className="fact"><small>Perfil</small><b>{account.profile}</b></div><div className="fact"><small>Origen</small><b>{account.source}</b></div><div className="fact"><small>Rol responsable</small><b>{owner&&roleLabels[owner.role]}</b></div></div></section>{assignmentHistory.some((item)=>item.opportunityId===opportunity.id)&&<section className="card detail-section"><h2>Historial de asignación</h2>{assignmentHistory.filter((item)=>item.opportunityId===opportunity.id).map((item)=><div className="assignment-row" key={item.id}><b>{users.find((user)=>user.id===item.newOwnerId)?.fullName}</b><small>{new Date(item.changedAt).toLocaleString("es-DO")} · {item.changeReason}</small></div>)}</section>}</aside></div>
    {assignOpen&&<Modal title="Asignar vendedor" description="El cambio quedará registrado para fines de control y comisión." onClose={()=>setAssignOpen(false)}><form onSubmit={submitAssignment}><div className="form-grid"><label className="field field-wide"><span>Vendedor responsable</span><select name="seller" defaultValue={opportunity.ownerId}>{users.filter((user)=>user.active&&["ejecutivo","gerencia_comercial","superadmin"].includes(user.role)).map((user)=><option value={user.id} key={user.id}>{user.fullName}</option>)}</select></label><label className="field field-wide"><span>Motivo de asignación</span><textarea name="reason" required placeholder="Nueva cartera, cobertura, especialidad…"/></label></div><div className="form-actions"><button type="button" className="button" onClick={()=>setAssignOpen(false)}>Cancelar</button><button className="button button-primary">Guardar asignación</button></div></form></Modal>}
    {closeOpen&&<Modal title="Confirmar cierre de venta" description="Se generará un reporte inmutable y la comisión del 50% sobre el primer honorario mensual cobrado." onClose={()=>setCloseOpen(false)}><form onSubmit={submitClose}><div className="form-grid"><label className="field"><span>Monto mensual final</span><input name="finalFee" type="number" min="1" step="0.01" defaultValue={defaultFee} required/></label><label className="field"><span>Fecha de cierre</span><input name="closedAt" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label className="field field-wide"><span>Contrato / referencia</span><input name="contractReference" placeholder="Contrato firmado, acta o referencia" required/></label><label className="field field-wide"><span>Notas del cierre</span><textarea name="notes" placeholder="Condiciones acordadas y próximos pasos…"/></label><label className="check-field field-wide"><input type="checkbox" name="firstPaymentReceived"/> Ya se recibió el primer honorario mensual</label></div><div className="form-actions"><button type="button" className="button" onClick={()=>setCloseOpen(false)}>Cancelar</button><button className="button button-primary">Cerrar y generar reporte</button></div></form></Modal>}
  </>;
}
