import type { Opportunity, OpportunityStage } from "@/types/domain";

export interface StagePlaybook {
  objective: string;
  actions: string[];
  exitCriteria: string[];
  coach: string;
  techniqueId: string;
}

export interface SalesTechnique {
  id: string;
  category: "Prospección" | "Diagnóstico" | "Persuasión ética" | "Negociación" | "Cierre" | "Seguimiento";
  title: string;
  summary: string;
  whenToUse: string;
  steps: string[];
  questions: string[];
  example: string;
  caution: string;
}

export const stagePlaybook: Record<OpportunityStage, StagePlaybook> = {
  prospecto_identificado: { objective: "Validar que la cuenta encaja con el servicio y localizar un contacto útil.", actions: ["Confirmar unidades, torres y ubicación", "Investigar administración actual", "Identificar un posible miembro de junta"], exitCriteria: ["Cuenta completa", "Contacto identificado"], coach: "No vendas todavía: gana el derecho a conversar demostrando que conoces el condominio.", techniqueId: "investigacion-3x3" },
  problema_detectado: { objective: "Convertir síntomas generales en un problema comercial concreto.", actions: ["Registrar el problema principal", "Cuantificar impacto operativo o financiero", "Confirmar urgencia percibida"], exitCriteria: ["Problema e impacto documentados", "Cliente reconoce la necesidad"], coach: "Pregunta por consecuencias y frecuencia; el dolor reconocido por el cliente es más convincente que un argumento del vendedor.", techniqueId: "spin" },
  contacto_decisor: { objective: "Comprender quién decide, quién influye y quién puede bloquear.", actions: ["Identificar presidente y tesorero", "Mapear postura e influencia", "Acordar acceso a la junta"], exitCriteria: ["Decisor confirmado", "Mapa de influencias actualizado"], coach: "Evita depender de un solo contacto. Construye consenso sin saltarte a tu aliado interno.", techniqueId: "mapa-decisores" },
  diagnostico: { objective: "Comprender la situación financiera, operativa y de convivencia antes de recomendar.", actions: ["Revisar morosidad y reportes", "Levantar mantenimiento e incidencias", "Definir resultado deseado"], exitCriteria: ["Diagnóstico completado", "Impacto y prioridad validados"], coach: "Resume lo escuchado y pide confirmación. El cliente debe sentir que la solución nace de su realidad.", techniqueId: "escucha-consultiva" },
  solucion_recomendada: { objective: "Vincular cada necesidad validada con una capacidad específica de INDEX CONDO.", actions: ["Priorizar tres resultados", "Diseñar alcance recomendado", "Seleccionar referencias comparables"], exitCriteria: ["Solución documentada", "Valor conectado al diagnóstico"], coach: "Habla de resultados antes que de características: confianza, control, continuidad y prevención.", techniqueId: "venta-valor" },
  presentacion: { objective: "Lograr acuerdo sobre el valor, el alcance y la viabilidad de la transición.", actions: ["Presentar diagnóstico antes de la solución", "Mostrar prueba social comparable", "Confirmar dudas y criterios de decisión"], exitCriteria: ["Presentación realizada", "Reacción y objeciones registradas"], coach: "La presentación debe sentirse como la conclusión lógica del diagnóstico, no como un discurso genérico.", techniqueId: "storytelling-cambio" },
  propuesta: { objective: "Entregar una propuesta clara con un siguiente paso y fecha definidos.", actions: ["Generar propuesta oficial", "Revisarla con el decisor", "Programar seguimiento en 48 horas"], exitCriteria: ["Propuesta enviada", "Seguimiento agendado"], coach: "Nunca envíes una propuesta sin acordar cuándo y cómo será revisada.", techniqueId: "avance-mutuo" },
  negociacion: { objective: "Resolver objeciones sin destruir el valor ni regalar margen.", actions: ["Clasificar la objeción real", "Defender alcance y resultados", "Registrar toda variación de precio"], exitCriteria: ["Condiciones acordadas", "Motivos de descuentos documentados"], coach: "Antes de rebajar, pregunta qué impide aprobar. Si concedes algo, solicita un compromiso equivalente.", techniqueId: "intercambio-condicional" },
  aprobacion: { objective: "Convertir el acuerdo verbal en una decisión formal de la junta.", actions: ["Confirmar aprobación y responsables", "Solicitar evidencia", "Definir fecha de firma"], exitCriteria: ["Aprobación verificable", "Firma programada"], coach: "Usa una pregunta de cierre directo y respetuoso: ¿qué requisito falta para autorizar el inicio?", techniqueId: "cierre-proximo-paso" },
  contrato_transicion: { objective: "Formalizar el contrato y reducir el riesgo percibido del cambio.", actions: ["Registrar contrato", "Acordar fecha de inicio", "Presentar plan de transición"], exitCriteria: ["Contrato firmado", "Inicio confirmado"], coach: "La claridad de la transición cierra ventas: responsables, fechas, información requerida y primeros entregables.", techniqueId: "reduccion-riesgo" },
  cliente_activo: { objective: "Asegurar una experiencia inicial que genere permanencia y referencias.", actions: ["Confirmar primer pago", "Documentar traspaso comercial", "Solicitar retroalimentación inicial"], exitCriteria: ["Primer pago recibido", "Reporte de venta generado"], coach: "El cierre no termina con la firma; una buena transición convierte la promesa comercial en confianza.", techniqueId: "expansion-confianza" },
  perdida: { objective: "Aprender de la decisión y conservar una relación profesional.", actions: ["Registrar motivo real", "Identificar competidor o alternativa", "Definir fecha de reactivación"], exitCriteria: ["Motivo documentado", "Aprendizaje compartido"], coach: "Pierde con elegancia: agradece, aprende y deja una puerta abierta sin perseguir al cliente.", techniqueId: "cierre-perdido" }
};

export const salesTechniques: SalesTechnique[] = [
  { id: "investigacion-3x3", category: "Prospección", title: "Investigación 3×3", summary: "Llegar al primer contacto con tres datos del condominio, tres hipótesis y tres preguntas útiles.", whenToUse: "Antes del primer contacto.", steps: ["Investiga tamaño, perfil y contexto", "Formula hipótesis sin asumir que son ciertas", "Abre con una observación relevante"], questions: ["¿Cómo gestionan hoy las incidencias recurrentes?", "¿Qué espera la junta de una administración ideal?"], example: "Vimos que el residencial tiene varias torres; ¿cómo coordinan actualmente mantenimiento y comunicación entre ellas?", caution: "No presentes información investigada como si fuera confirmada por el cliente." },
  { id: "spin", category: "Diagnóstico", title: "Preguntas SPIN", summary: "Explorar situación, problema, implicación y necesidad de solución.", whenToUse: "Cuando el cliente reconoce síntomas pero todavía no prioriza el cambio.", steps: ["Comprende la situación", "Profundiza el problema", "Cuantifica consecuencias", "Haz visible el valor del cambio"], questions: ["¿Qué ocurre cuando un reporte llega tarde?", "¿Cómo afecta eso la confianza de los propietarios?"], example: "Si la morosidad continúa igual seis meses, ¿qué mantenimiento tendría que posponerse?", caution: "No conviertas el diagnóstico en interrogatorio; escucha y resume." },
  { id: "mapa-decisores", category: "Diagnóstico", title: "Mapa de decisores", summary: "Identificar poder, interés, postura y relación entre los participantes.", whenToUse: "En compras aprobadas por juntas o comités.", steps: ["Identifica autoridad formal", "Detecta influenciadores", "Comprende criterios individuales", "Construye consenso"], questions: ["¿Quién debe sentirse cómodo para aprobar?", "¿Qué criterio será más importante para el tesorero?"], example: "Además de usted, ¿quién evaluará el componente financiero y quién la transición operativa?", caution: "No uses el mapa para dividir a la junta ni manipular relaciones internas." },
  { id: "escucha-consultiva", category: "Diagnóstico", title: "Escucha consultiva", summary: "Escuchar, reflejar, confirmar y priorizar antes de recomendar.", whenToUse: "Durante toda reunión de descubrimiento.", steps: ["Pregunta de forma abierta", "Profundiza con ejemplos", "Resume con palabras del cliente", "Pide confirmación"], questions: ["¿Puede darme un ejemplo reciente?", "De todo lo mencionado, ¿qué resolvería primero?"], example: "Lo que escucho es que el problema no es solo la avería, sino no saber quién responde. ¿Es correcto?", caution: "No finjas empatía ni uses información sensible fuera del propósito comercial acordado." },
  { id: "venta-valor", category: "Persuasión ética", title: "Venta basada en valor", summary: "Traducir capacidades en resultados relevantes para la junta y los propietarios.", whenToUse: "Al diseñar y presentar la solución.", steps: ["Recuerda la necesidad validada", "Conecta una capacidad", "Describe el resultado", "Aporta evidencia"], questions: ["¿Qué cambiaría si la junta recibe reportes confiables cada mes?", "¿Cómo valoran reducir emergencias evitables?"], example: "El plan preventivo no es una lista de visitas; busca reducir averías, gastos imprevistos y fricción con propietarios.", caution: "No inventes ahorros ni garantices resultados fuera del control de INDEX CONDO." },
  { id: "storytelling-cambio", category: "Persuasión ética", title: "Historia de cambio", summary: "Presentar situación actual, riesgo, camino de transición y resultado futuro.", whenToUse: "En presentaciones ante la junta.", steps: ["Describe el presente validado", "Explica el costo de continuar igual", "Muestra el camino", "Visualiza un resultado creíble"], questions: ["¿Este escenario refleja su situación?", "¿Qué parte del cambio les genera más incertidumbre?"], example: "Hoy la junta reacciona a incidencias; proponemos pasar a una operación con responsables, calendario y reportes visibles.", caution: "La urgencia debe basarse en riesgos reales, nunca en miedo exagerado o falsa escasez." },
  { id: "avance-mutuo", category: "Seguimiento", title: "Plan de avance mutuo", summary: "Acordar con el cliente pasos, responsables y fechas hasta la decisión.", whenToUse: "Antes de enviar la propuesta.", steps: ["Confirma el proceso de decisión", "Define responsables", "Acorda fechas", "Registra el próximo paso"], questions: ["¿Cuándo la revisará la junta?", "¿Qué información necesitan antes de votar?"], example: "Enviamos hoy, revisamos dudas el martes y, si el alcance está correcto, coordinamos presentación a la junta.", caution: "El plan es colaborativo; no impongas fechas que el cliente no aceptó." },
  { id: "intercambio-condicional", category: "Negociación", title: "Concesión condicionada", summary: "Evitar descuentos gratuitos intercambiando cada concesión por un compromiso verificable.", whenToUse: "Cuando solicitan reducción de precio o cambio de alcance.", steps: ["Aclara la objeción", "Defiende el valor", "Explora alternativas", "Condiciona cualquier concesión"], questions: ["Si resolvemos este punto, ¿estarían en posición de aprobar?", "¿Prefieren ajustar alcance o mantener el plan completo?"], example: "Podemos evaluar ese ajuste si confirmamos el contrato anual y la fecha de inicio acordada.", caution: "No ocultes condiciones ni uses anclajes artificiales; registra cada cambio con transparencia." },
  { id: "cierre-proximo-paso", category: "Cierre", title: "Cierre por próximo paso", summary: "Transformar acuerdo general en una acción concreta sin presión indebida.", whenToUse: "Cuando valor, alcance y objeciones ya están resueltos.", steps: ["Resume acuerdos", "Pregunta qué falta", "Propón la acción natural", "Confirma responsable y fecha"], questions: ["¿Qué requisito falta para autorizar el inicio?", "¿Podemos fijar hoy la fecha de firma?"], example: "Ya validamos alcance, transición y honorarios. ¿Coordinamos la firma para el miércoles?", caution: "Acepta un no claro; no uses culpa, hostigamiento ni falsas urgencias." },
  { id: "reduccion-riesgo", category: "Cierre", title: "Reducción de riesgo", summary: "Disminuir incertidumbre explicando exactamente cómo será la transición.", whenToUse: "Cuando el cliente quiere cambiar pero teme interrupciones.", steps: ["Enumera riesgos", "Asigna responsables", "Presenta cronograma", "Define controles y comunicación"], questions: ["¿Qué no puede fallar durante el cambio?", "¿Quién debe recibir actualizaciones de transición?"], example: "Durante los primeros 30 días tendremos inventario, calendario, responsables y reporte semanal a la junta.", caution: "No prometas una transición sin dificultades; explica también dependencias del cliente." },
  { id: "expansion-confianza", category: "Seguimiento", title: "Expansión por confianza", summary: "Convertir una buena incorporación en permanencia, referencias y nuevas oportunidades.", whenToUse: "Después de la firma y durante el arranque.", steps: ["Cumple primeros compromisos", "Solicita retroalimentación", "Documenta resultados", "Pide referencia en el momento adecuado"], questions: ["¿Qué ha sido más útil hasta ahora?", "¿Qué otro condominio podría beneficiarse de este proceso?"], example: "Una vez entregado el primer reporte, validemos juntos qué mejorar y qué valor percibió la junta.", caution: "No solicites referencias antes de haber entregado valor verificable." },
  { id: "cierre-perdido", category: "Seguimiento", title: "Cierre profesional de oportunidad perdida", summary: "Aprender, preservar la relación y establecer una reactivación razonable.", whenToUse: "Cuando el cliente decide no continuar.", steps: ["Agradece con sinceridad", "Solicita aprendizaje", "Registra el motivo", "Acorda permiso para retomar"], questions: ["¿Qué pesó más en la decisión?", "¿Sería apropiado conversar nuevamente más adelante?"], example: "Gracias por la transparencia. Para mejorar, ¿qué factor hizo que otra alternativa encajara mejor?", caution: "No discutas la decisión ni desacredites al competidor." }
];

export function recommendationForOpportunity(opportunity: Opportunity) {
  const playbook = stagePlaybook[opportunity.stage];
  const staleDays = Math.floor((Date.now() - new Date(opportunity.updatedAt).getTime()) / 86_400_000);
  if (staleDays >= 7) return `Esta oportunidad lleva ${staleDays} días sin actualización. Retoma contacto con una pregunta de valor y acuerda un próximo paso.`;
  if (!opportunity.nextAction || !opportunity.nextActionAt) return "Define ahora una próxima acción con responsable y fecha; una oportunidad sin siguiente paso está detenida.";
  if (opportunity.stage === "propuesta") return "Confirma recepción y agenda una revisión dentro de 48 horas. No dejes la propuesta sin conversación.";
  if (opportunity.stage === "negociacion") return "Aísla la objeción real antes de modificar precio. Toda concesión debe recibir un compromiso equivalente.";
  return playbook.coach;
}
