"use client";
import Link from "next/link";
import { ArrowRight, CalendarClock, CircleDollarSign, FileText, Target, TrendingUp } from "lucide-react";
import { useCrm } from "@/components/crm-provider";
import { PageHeader, StagePill } from "@/components/ui";
import { canSeeOpportunity } from "@/lib/permissions";
import { formatCurrency } from "@/lib/constants";

export default function Dashboard() {
  const { opportunities, accounts, tasks, proposals, currentUser } = useCrm();
  const visible = opportunities.filter((o) => canSeeOpportunity(currentUser, o) && !["cliente_activo", "perdida"].includes(o.stage));
  const pipeline = visible.reduce((sum, item) => sum + item.monthlyFee, 0); const weighted = visible.reduce((sum, item) => sum + item.monthlyFee * item.probability / 100, 0);
  const pending = tasks.filter((t) => t.status !== "completada" && visible.some((o) => o.id === t.opportunityId));
  const account = (id: string) => accounts.find((a) => a.id === id)!;
  return <><PageHeader eyebrow="Centro comercial B2B" title={`Buenos días, ${currentUser.fullName.split(" ")[0]}`} description="Prioridades, valor del embudo y próximas acciones para vender soluciones de administración condominial."/>
    <section className="grid kpi-grid"><article className="card kpi-card"><div className="kpi-top"><span className="kpi-label">Oportunidades activas</span><span className="kpi-icon"><Target size={19}/></span></div><div className="kpi-value">{visible.length}</div><div className="kpi-foot">+2 durante los últimos 30 días</div></article><article className="card kpi-card"><div className="kpi-top"><span className="kpi-label">Valor mensual del embudo</span><span className="kpi-icon"><CircleDollarSign size={19}/></span></div><div className="kpi-value">{formatCurrency(pipeline)}</div><div className="kpi-foot">{formatCurrency(pipeline * 12)} anual potencial</div></article><article className="card kpi-card"><div className="kpi-top"><span className="kpi-label">Forecast ponderado</span><span className="kpi-icon"><TrendingUp size={19}/></span></div><div className="kpi-value">{formatCurrency(weighted)}</div><div className="kpi-foot">Basado en probabilidad de cierre</div></article><article className="card kpi-card"><div className="kpi-top"><span className="kpi-label">Seguimientos pendientes</span><span className="kpi-icon"><CalendarClock size={19}/></span></div><div className="kpi-value">{pending.length}</div><div className="kpi-foot">{pending.filter((t) => t.status === "vencida").length} requiere atención hoy</div></article></section>
    <section className="grid dashboard-grid"><div className="card"><div className="section-head"><div><h2>Oportunidades prioritarias</h2><p>Ordenadas por etapa, valor y próxima acción</p></div><Link className="text-link" href="/embudo">Ver embudo <ArrowRight size={13}/></Link></div><div className="table-wrap"><table className="table"><thead><tr><th>Cuenta</th><th>Necesidad</th><th>Etapa</th><th>Honorarios</th><th>Próxima acción</th></tr></thead><tbody>{visible.slice(0,6).map((o) => <tr key={o.id}><td><Link href={`/prospectos/${o.accountId}`}><strong>{account(o.accountId).name}</strong><small>{account(o.accountId).units} unidades · {account(o.accountId).sector}</small></Link></td><td>{o.primaryProblem}</td><td><StagePill stage={o.stage}/></td><td className="amount">{formatCurrency(o.monthlyFee)}</td><td><strong>{o.nextAction}</strong><small>{new Date(o.nextActionAt).toLocaleDateString("es-DO",{day:"2-digit",month:"short"})}</small></td></tr>)}</tbody></table></div></div>
      <aside className="grid"><div className="card"><div className="section-head"><div><h2>Próximas acciones</h2><p>Lo que mueve cada oportunidad</p></div><Link className="text-link" href="/tareas">Ver todas</Link></div><div className="next-list">{pending.slice(0,4).map((task) => { const opportunity=opportunities.find((o)=>o.id===task.opportunityId)!; const date=new Date(task.dueAt); return <div className="next-item" key={task.id}><div className="date-box"><b>{date.getDate()}</b><small>{date.toLocaleDateString("es-DO",{month:"short"})}</small></div><div><strong><span className={`priority priority-${task.priority}`}/>{task.title}</strong><p>{account(opportunity.accountId).name}</p></div></div>})}</div></div><div className="card"><div className="section-head"><div><h2>Propuestas</h2><p>Actividad comercial reciente</p></div><FileText size={19} color="#f47721"/></div><div className="card-pad" style={{paddingTop:0}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span className="kpi-label">Generadas</span><b>{proposals.length}</b></div><div className="metric-bar"><span style={{width:"66%"}}/></div><div className="pipeline-mini"><span style={{height:"35%"}}/><span style={{height:"48%"}}/><span className="hot" style={{height:"78%"}}/><span style={{height:"62%"}}/><span className="hot" style={{height:"90%"}}/><span style={{height:"70%"}}/></div></div></div></aside></section>
  </>;
}
