"use client";
import Link from "next/link";
import { Filter, GripVertical, Lightbulb, UserRound } from "lucide-react";
import { useState } from "react";
import { useCrm } from "@/components/crm-provider";
import { PageHeader } from "@/components/ui";
import { formatCurrency, pipelineStages, stageLabels } from "@/lib/constants";
import { canSeeOpportunity } from "@/lib/permissions";
import { stagePlaybook } from "@/lib/sales-playbook";
import type { OpportunityStage } from "@/types/domain";

export default function EmbudoPage(){const {opportunities,accounts,users,currentUser,updateOpportunity}=useCrm();const [dragged,setDragged]=useState<string|null>(null);const visible=opportunities.filter((o)=>canSeeOpportunity(currentUser,o)&&o.stage!=="perdida");function drop(stage:OpportunityStage){if(dragged)updateOpportunity(dragged,{stage});setDragged(null)}return <><PageHeader eyebrow="Venta consultiva" title="Embudo de soluciones" description="Cada etapa indica qué debe lograr el vendedor antes de avanzar. Abre el prospecto para ver recomendaciones contextuales."><button className="button"><Filter size={17}/> Filtrar cartera</button></PageHeader><div className="kanban">{pipelineStages.map((stage)=><section className="kanban-column" key={stage} onDragOver={(e)=>e.preventDefault()} onDrop={()=>drop(stage)}><header className="kanban-head"><div><b>{stageLabels[stage]}</b><small>{stagePlaybook[stage].objective}</small></div><span className="count">{visible.filter((o)=>o.stage===stage).length}</span></header>{visible.filter((o)=>o.stage===stage).map((opportunity)=>{const account=accounts.find((a)=>a.id===opportunity.accountId)!;const owner=users.find((user)=>user.id===opportunity.ownerId);return <article className="deal" key={opportunity.id} draggable onDragStart={()=>setDragged(opportunity.id)}><div className="deal-title"><Link href={`/prospectos/${account.id}`}><h3>{account.name}</h3></Link><GripVertical size={15} color="#a6b1bd"/></div><p>{opportunity.primaryProblem}</p><div className="deal-owner"><UserRound size={12}/>{owner?.fullName??"Sin asignar"}</div><div className="deal-value">{formatCurrency(opportunity.monthlyFee)} <small>/mes</small></div><div className="deal-meta"><span>{account.units} unidades</span><b>{opportunity.probability}%</b></div><div className="progress full-progress"><span style={{width:`${opportunity.probability}%`}}/></div><div className="deal-action">Próximo: {opportunity.nextAction}</div><Link className="deal-coach" href={`/prospectos/${account.id}`}><Lightbulb size={12}/> Ver recomendación de cierre</Link></article>})}</section>)}</div></>}
